#Final Shiny App
library(shiny)
library(tidyverse)
library(ggrepel)
library(rsconnect)
library(randomForest)
library(DT)

tot_career <- read.csv(file = "total_career copy.csv")
#names_dfs <- read.csv(file = "full_names copy.csv") ##This file is not complete and isn't being used
mod_res <- read.csv(file = "rf_results copy.csv")
mod <- readRDS("model copy.rds")

choice_list <- unique(mod_res %>%
                        select(player))

ui <- shinyUI(
  fluidPage(
    
    titlePanel("Potter Sports Group: Predicting NBA Players"),
    
    mainPanel(
      column(12, 
             tabsetPanel(
               tabPanel("Lead Generator", 
                        fluidRow(downloadButton("download","Download the data"),
                                 DT::dataTableOutput("playerList"),
                                 wellPanel(
                                   sliderInput(inputId = "topn",
                                               label = "Select % Chance",
                                               min = 1,
                                               max = 99,
                                               value = 20,
                                               step = 1),
                                   sliderInput(inputId = "agen",
                                               label = "Age or younger:",
                                               min = 18,
                                               max = 35,
                                               value = 25,
                                               step = 1),
                                   sliderInput(inputId = "mpn",
                                               label = "Max Minutes Played Per Game",
                                               min = 0,
                                               max = 35,
                                               value = 35,
                                               step = .5)
                                 )
                        )
               ),
               tabPanel("Input a Player", 
                        fluidRow(textOutput("iPlayer"),
                                 tags$head(tags$style("#iPlayer{color: black;
                                                      font-size: 30px;
                                                      font-style: bold;
                                                      }")
                                           ),
                                 wellPanel(
                                   textInput(inputId = "name",
                                             label = "Player Name",
                                             value = "Player X"),
                                   sliderInput(inputId = "age",
                                               label = "Age",
                                               min = 18,
                                               max = 35,
                                               value = 29,
                                               step = 1),
                                   htmlOutput("selectSchool"),
                                   sliderInput(inputId = "sos",
                                               label = "Strength of Schedule",
                                               min = -15,
                                               max = 15,
                                               value = -.5,
                                               step = .25),
                                   sliderInput(inputId = "pts",
                                               label = "Points Per Game",
                                               min = 0,
                                               max = 35,
                                               value = 5,
                                               step = .5),
                                   sliderInput(inputId = "g",
                                               label = "Games Played",
                                               min = 1,
                                               max = 160,
                                               value = 59,
                                               step = 1),
                                   sliderInput(inputId = "gs",
                                               label = "Games Started",
                                               min = 1,
                                               max = 150,
                                               value = 29,
                                               step = 1),
                                   sliderInput(inputId = "mp",
                                               label = "Minutes Per Game",
                                               min = 0,
                                               max = 40,
                                               value = 15,
                                               step = .5),
                                   sliderInput(inputId = "ast",
                                               label = "Assists Per Game",
                                               min = 0,
                                               max = 9,
                                               value = 1,
                                               step = .5),
                                   sliderInput(inputId = "orb",
                                               label = "Offensive Rebounds Per Game",
                                               min = 0,
                                               max = 6,
                                               value = 1,
                                               step = .5),
                                   sliderInput(inputId = "drb",
                                               label = "Defensive Rebounds Per Game",
                                               min = 0,
                                               max = 9,
                                               value = 1.5,
                                               step = .5),
                                   sliderInput(inputId = "trb",
                                               label = "Total Rebounds Per Game",
                                               min = 0,
                                               max = 13,
                                               value = 2.5,
                                               step = .5),
                                   sliderInput(inputId = "stl",
                                               label = "Steals Per Game",
                                               min = 0,
                                               max = 5,
                                               value = .5,
                                               step = .5),
                                   sliderInput(inputId = "blk",
                                               label = "Blocks Per Game",
                                               min = 0,
                                               max = 6,
                                               value = .25,
                                               step = .25),
                                   sliderInput(inputId = "tov",
                                               label = "Turnovers Per Game",
                                               min = 0,
                                               max = 6,
                                               value = 1,
                                               step = .5),
                                   sliderInput(inputId = "fg",
                                               label = "Field Goals Made",
                                               min = 0,
                                               max = 10,
                                               value = 2,
                                               step = .25),
                                   sliderInput(inputId = "fga",
                                               label = "Field Goal Attempts Per Game",
                                               min = 0,
                                               max = 21.5,
                                               value = 4,
                                               step = .5),
                                   sliderInput(inputId = "fg_2",
                                               label = "Field Goal Percentage",
                                               min = 0,
                                               max = 100,
                                               value = 41,
                                               step = .5),
                                   sliderInput(inputId = "x2p",
                                               label = "2 Points Made Per Game",
                                               min = 0,
                                               max = 10,
                                               value = .5,
                                               step = .25),
                                   sliderInput(inputId = "x2pa",
                                               label = "2 Point Attempts Per Game",
                                               min = 0,
                                               max = 20,
                                               value = 3,
                                               step = .5),
                                   sliderInput(inputId = "x2p_2",
                                               label = "2 Point Percentage",
                                               min = 0,
                                               max = 100,
                                               value = 45,
                                               step = .5),
                                   sliderInput(inputId = "x3p",
                                               label = "3 Points Made Per Game",
                                               min = 0,
                                               max = 4,
                                               value = .5,
                                               step = .5),
                                   sliderInput(inputId = "x3pa",
                                               label = "3 Point Attempts Per Game",
                                               min = 0,
                                               max = 11,
                                               value = 1.5,
                                               step = .5),
                                   sliderInput(inputId = "x3p_2",
                                               label = "3 Point Percentage",
                                               min = 0,
                                               max = 100,
                                               value = 28,
                                               step = .5),
                                   sliderInput(inputId = "ft",
                                               label = "Free Throws Made Per Game",
                                               min = 0,
                                               max = 8,
                                               value = 1,
                                               step = .5),
                                   sliderInput(inputId = "fta",
                                               label = "Free Throw Attempts Per Game",
                                               min = 0,
                                               max = 10,
                                               value = 1.5,
                                               step = .5),
                                   sliderInput(inputId = "ft_2",
                                               label = "Free Throws Percentage",
                                               min = 0,
                                               max = 100,
                                               value = 64,
                                               step = .5),
                                   sliderInput(inputId = "pf",
                                               label = "Personal Fouls Per Game",
                                               min = 0,
                                               max = 5,
                                               value = 1.5,
                                               step = .5)
                                 )
                        )
               ),
               tabPanel("Select a Player", 
                        fluidRow(tableOutput("rPlayer"),
                                 # actionButton("showChart", "Show Chart"),
                                 selectizeInput(inputId = "playerR",
                                                label = "Select Player",
                                                choices = choice_list,
                                                options = list(maxOptions = 30000))
                        )
               )
             )
      ),
      width = 12)
  )
)